### ISSUE TITLE
Images as itemize labels in slides

### ISSUE THREAD

**Issue by asbates** [asbates/bayes-time-series#1]
What if we replace the bullets in the itemize environment with images of say, swords, bags of gold, potion, etc? It would fit more into the theme we're going for and [this post](https://tex.stackexchange.com/questions/12735/can-one-replace-bullet-points-with-graphics) makes it seem like it would be easy to do.

**Comment by tylertucker202** [comment]
I'm on it. Its not quite done, but we can make it happen soon.

**Comment by asbates** [comment]
Closes #1
